# Generated by Django 2.1.2 on 2018-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tour', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('descripción', models.TextField()),
                ('comentario', models.TextField()),
                ('imagen', models.ImageField(upload_to='tours', verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Tours',
                'verbose_name_plural': 'Tours',
                'ordering': ['-creacion'],
            },
        ),
    ]
