# Generated by Django 2.1.2 on 2018-11-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.TextField()),
                ('imagen', models.ImageField(upload_to='tours/banners', verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'tour_banners',
                'verbose_name_plural': 'tour_banners',
                'ordering': ['-creacion'],
            },
        ),
    ]
