# Generated by Django 2.1.2 on 2018-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='recomendado',
            field=models.BooleanField(null=True),
        ),
    ]
