# Generated by Django 2.1.2 on 2018-12-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_recomendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
