# Generated by Django 2.1.2 on 2018-12-10 17:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20181207_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='comentario',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='costo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripción',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
