# Generated by Django 2.1.2 on 2018-12-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20181210_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='tours.tour')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'Slider detalle',
            },
        ),
    ]
