# Generated by Django 2.1.2 on 2018-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=50)),
                ('nombre_hotel', models.CharField(max_length=50)),
                ('capacidad_habitacion', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=3, max_digits=5)),
                ('descripción', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
