# Generated by Django 2.1.2 on 2018-11-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_hoteles_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hoteles',
            new_name='Hotele',
        ),
    ]
