# Generated by Django 2.1.2 on 2018-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0008_hotel_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_banners',
            name='imagen',
            field=models.ImageField(upload_to='hoteles/banners', verbose_name='Imagen'),
        ),
    ]
