# Generated by Django 2.1.2 on 2018-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0009_auto_20181127_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotele',
            name='recomendado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
