# Generated by Django 2.1.2 on 2018-12-10 04:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0010_hotele_recomendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotele',
            name='descripción',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
