# Generated by Django 2.1.2 on 2018-12-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0013_imagenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'Slider detalle'},
        ),
    ]
