# Generated by Django 2.1.2 on 2018-11-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excursiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_excursion', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('salida', models.CharField(max_length=50)),
                ('itinerario', models.CharField(max_length=50)),
                ('capacidad_maxima', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('imagen', models.ImageField(upload_to='excursiones', verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Excursiones',
                'verbose_name_plural': 'Excursiones',
                'ordering': ['-creacion'],
            },
        ),
    ]
