# Generated by Django 2.1.2 on 2018-12-10 05:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0003_excursiones_recomendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursiones',
            name='costo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='excursiones',
            name='itinerario',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
