# Generated by Django 2.1.2 on 2018-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0004_auto_20181210_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursiones',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='excursiones',
            name='itinerario',
            field=models.CharField(max_length=50),
        ),
    ]
